name: Continuous Integration
on: [push, pull_request]

env:
  DEBUG: true

jobs:
  unit-test:
    name: Unit Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [10, 12]
        exclude:
          - os: macos-latest
            node: 10
      max-parallel: 1
    runs-on: ${{ matrix.os }}
    container:
      image: node:12.14.1-stretch
      env:
        NODE_ENV: development
      ports:
        - 8080
      options: --cpus 1
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    timeout-minutes: 30
    env:
      DEBUG: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1.3.0
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
        env:
          DEBUG: true
      - name: Test
        run: npm test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Node.js 12.x
        uses: actions/setup-node@v1.3.0
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  sleep:
    name: Sleep 120s
    runs-on: ubuntu-16.04
    steps:
      - name: Sleep
        run: sleep 120
        timeout-minutes: 1
        continue-on-error: true
  secret:
    name: Show Secret Token
    runs-on: macos-latest
    needs: [unit-test, lint, sleep]
    steps:
      - run: echo "${{ secrets.SECRET_TOKEN }}"